/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.Project;
import model.Task;


/**
 *
 * @author mateus.perpetuo
 */
public class EditTaskDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditTaskDialog
     */
    
    TaskController controller;
    Project project;
    Task task;
    private String tname;
    
    public EditTaskDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();              
        // Starting a new instance for the controller
        controller = new TaskController();  
        hideErrorFileds();
        initFieldsData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHead = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        scrollDescription = new javax.swing.JScrollPane();
        txtAreaDescription = new javax.swing.JTextArea();
        lblDeadline = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        scrollNotes = new javax.swing.JScrollPane();
        txtAreaNotes = new javax.swing.JTextArea();
        formattedTxtDeadline = new javax.swing.JFormattedTextField();
        lblDeadlineMandatory = new java.awt.Label();
        lblNameMandatory = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlHead.setBackground(new java.awt.Color(0, 153, 102));
        pnlHead.setForeground(java.awt.Color.white);

        btnSave.setBackground(new java.awt.Color(0, 153, 102));
        btnSave.setForeground(java.awt.Color.white);
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diskette.png"))); // NOI18N
        btnSave.setBorder(null);
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(java.awt.Color.white);
        lblTitle.setText("Edit Task");

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlBody.setBackground(java.awt.Color.white);

        lblName.setBackground(java.awt.Color.black);
        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setForeground(java.awt.Color.black);
        lblName.setText("Name: ");

        txtName.setBackground(java.awt.Color.white);
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.setForeground(java.awt.Color.black);
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblDescription.setBackground(java.awt.Color.black);
        lblDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDescription.setForeground(java.awt.Color.black);
        lblDescription.setText("Description:");

        txtAreaDescription.setBackground(java.awt.Color.white);
        txtAreaDescription.setColumns(20);
        txtAreaDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAreaDescription.setForeground(java.awt.Color.black);
        txtAreaDescription.setRows(5);
        scrollDescription.setViewportView(txtAreaDescription);

        lblDeadline.setBackground(java.awt.Color.black);
        lblDeadline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDeadline.setForeground(java.awt.Color.black);
        lblDeadline.setText("Deadline: *");

        lblNotes.setBackground(java.awt.Color.black);
        lblNotes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNotes.setForeground(java.awt.Color.black);
        lblNotes.setText("Notes:");

        txtAreaNotes.setBackground(java.awt.Color.white);
        txtAreaNotes.setColumns(20);
        txtAreaNotes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAreaNotes.setForeground(java.awt.Color.black);
        txtAreaNotes.setRows(5);
        scrollNotes.setViewportView(txtAreaNotes);

        formattedTxtDeadline.setBackground(java.awt.Color.white);
        formattedTxtDeadline.setForeground(java.awt.Color.black);
        formattedTxtDeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        formattedTxtDeadline.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        formattedTxtDeadline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblDeadlineMandatory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDeadlineMandatory.setForeground(java.awt.Color.red);
        lblDeadlineMandatory.setText("The deadline field is mandatory!");

        lblNameMandatory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNameMandatory.setForeground(java.awt.Color.red);
        lblNameMandatory.setText("The Name field is mandatory!");

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeadlineMandatory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(lblDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollNotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(formattedTxtDeadline)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescription)
                            .addComponent(lblNotes))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblNameMandatory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNameMandatory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattedTxtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDeadlineMandatory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked

        // Command is placed within an error handling method because it's known that errors can occur
        try {

            if (isFieldValid()){
               
                // Collecting the informaticon the user typed
                task.setId(task.getId());
                task.setName(txtName.getText());
                task.setDescription(txtAreaDescription.getText());
                task.setNotes(txtAreaNotes.getText());
                task.setIsCompleted(false);
                task.setUpdatedAt(new Date());
                
                /**
                * This code allows the task processing to access the project
                * and collect its ID ( The project classe is being started in
                    * the last block of the code page )
                **/
                
                task.setIdProject(project.getId());            

                /**
                * Process to extract a date string from the text field,
                * parsing it into a Date object using the specified date format
                **/
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline = null;
                deadline = dateFormat.parse(formattedTxtDeadline.getText());
                task.setDeadline(deadline);

                // Saving to the database
                controller.update(task);

                // Showing a succefull mensage
                JOptionPane.showMessageDialog(rootPane, "Task updated successfully");

                // Closing the window
                this.dispose();

            } else {

                hideErrorFileds();

                if(txtName.getText().isEmpty()){
                    lblNameMandatory.setVisible(true);
                    pnlBody.revalidate();
                }

                if(formattedTxtDeadline.getText().isEmpty()){
                    lblDeadlineMandatory.setVisible(true);
                    pnlBody.revalidate();
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTaskDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTaskDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTaskDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTaskDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditTaskDialog dialog = new EditTaskDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JFormattedTextField formattedTxtDeadline;
    private javax.swing.JLabel lblDeadline;
    private java.awt.Label lblDeadlineMandatory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private java.awt.Label lblNameMandatory;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JScrollPane scrollDescription;
    private javax.swing.JScrollPane scrollNotes;
    private javax.swing.JTextArea txtAreaDescription;
    private javax.swing.JTextArea txtAreaNotes;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    
    public void setProject(Project project) {
        this.project = project;
    }
    public void setTask(Task task){
        this.task = task;   
    }


    public void hideErrorFileds(){
        lblDeadlineMandatory.setVisible(false);
        lblNameMandatory.setVisible(false);
    }
    
    public boolean isFieldValid(){        
        return ! txtName.getText().isEmpty() && ! formattedTxtDeadline.getText().isEmpty();
        
    }
    public void setName(String tname){
        String getTaskname;
        getTaskname = this.tname;
        txtName.setText(getTaskname);
    }
    
    
    private void initFieldsData(){
        
        try{
            task.getId();
            task.setIdProject(project.getId());
        
          /*  txtName.setText(task.getName());
            txtAreaDescription.setText(task.getDescription());
            txtAreaNotes.setText(task.getNotes());*/
       
        // formattedTxtDeadline.setText(task.getDeadline()); 
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        
    }
}   

