/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import controller.TaskController;
import model.Project;
import model.Task;

import java.util.Date;
import java.util.List;

public class App {
   public static void main(String[] args) {

        // teste the aplication

        ProjectController projectController = new ProjectController();

        Project project= new Project();
        project.setId(1);
        project.setName("Teste");
        
        projectController.update(project);
        

        //lista dos projetos
        List<Project> projects =  projectController.getALL();
        System.out.println("Total de projetos = " + projects.size());

        TaskController taskController= new TaskController();

        Task task = new Task();
        task.setIdProject(1);
        task.setId(1);
        task.setName("Test");
        task.setNotes("testing");
        task.setDescription("testing");
        task.setIsCompleted(false);
        task.setUpdatedAt(new Date());
        task.setDeadline(new Date());

        taskController.update(task);

        List<Task> tasks = taskController.getAll(1);
        System.out.println("Total de Task desse projeto "+ tasks.size());

        }
}
